#cloud-config
package_update: true
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - git

runcmd:
  # Добавляем официальный GPG ключ Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  
  # Добавляем репозиторий Docker
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  
  # Обновляем индекс пакетов
  - apt-get update
  
  # Устанавливаем Docker
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  
  # Запускаем и включаем Docker
  - systemctl start docker
  - systemctl enable docker
  
  # Добавляем пользователя ubuntu в группу docker
  - usermod -aG docker ubuntu
  
  # Устанавливаем Docker Compose
  - curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  
  # Создаем символическую ссылку
  - ln -sf /usr/local/bin/docker-compose /usr/bin/docker-compose
  
  # Ждем немного для стабилизации
  - sleep 30
  
  # Ждем доступности менеджера и получаем токен
  - while ! curl -s http://${manager_ip}:8080/worker_token > /dev/null; do sleep 10; done
  
  # Получаем токен и присоединяемся к кластеру
  - curl -s http://${manager_ip}:8080/worker_token > /tmp/worker_token
  - docker swarm join --token $(cat /tmp/worker_token) ${manager_ip}:2377
  
  # Проверяем статус
  - docker node ls
  
  # Клонируем репозиторий sock-shop
  - git clone https://github.com/Meskaline213/dockerswarm_socks_full.git /home/ubuntu/sock-shop
  # Исправляем права на директорию
  - chown -R ubuntu:ubuntu /home/ubuntu/sock-shop 