#cloud-config
package_update: true
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

runcmd:
  # Добавляем официальный GPG ключ Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  
  # Добавляем репозиторий Docker
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  
  # Обновляем индекс пакетов
  - apt-get update
  
  # Устанавливаем Docker
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  
  # Запускаем и включаем Docker
  - systemctl start docker
  - systemctl enable docker
  
  # Добавляем пользователя ubuntu в группу docker
  - usermod -aG docker ubuntu
  
  # Устанавливаем Docker Compose
  - curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  
  # Создаем символическую ссылку
  - ln -sf /usr/local/bin/docker-compose /usr/bin/docker-compose
  
  # Проверяем установку
  - docker --version
  - docker-compose --version 